### ISSUE TITLE
AtomikosDataSoureBean datasource null

### ISSUE THREAD

**Issue by denizque** [jaxio/angular-lab#20]
Hi,

When generating the project receiving info as:

[INFO] com.atomikos.jdbc.AbstractDataSourceBean - AtomikosDataSoureBean 'dataSource': getConnection ( null )...
[DEBUG] com.atomikos.icatch.imp.BaseTransactionManager - getCompositeTransaction() returning NULL!

Unable to start the generated app.

**Comment by AVE-cesar** [comment]
I will try to reproduce you error and give you an answer soon; Stay tuned !

**Comment by AVE-cesar** [comment]
I am not able to reproduce your error.

can you explain me the steps you've done ?

thanks

**Comment by denizque** [comment]
I did the steps in readme.
bower install
mvn -Pdb,metadata,gen
and generated successfully.
Then tried starting with:
mvn spring-boot:run

but the project doesn't start. In pom.xml I see the database as H2.
a month ago or two when I tried to generate and start it was working successfully..

**Comment by AVE-cesar** [comment]
can you give me the log file of your spring boot server startup ?

**Comment by AVE-cesar** [comment]
can you try this ?

uncomment this dependency inside your pom.xml file and restart you spring boot app:

**Comment by denizque** [comment]
by this dependency you mean?

**Comment by AVE-cesar** [comment]
1. Open your file named pom.xml (root of your project)
2. Search for "spring-boot-starter-jta-atomikos" (approx line 203)
3. Comment this maven dependency:

```
<!-- dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jta-atomikos</artifactId>
        </dependency-->
```
1. restart your boot app

**Comment by denizque** [comment]
It's already uncommented.

I pasted the log here:
http://pastebin.com/eXvqXMVm

**Comment by denizque** [comment]
Here's the log:

http://pastebin.com/urR66eTU

**Comment by AVE-cesar** [comment]
I haven't got access to this kind of URL because of security restrictions

can you send me an email at custom.mail.bave in gmail.com ?

**Comment by AVE-cesar** [comment]
there is no error inside your log
try  **[http://127.0.0.1:8080/myApp](http://127.0.0.1:8080/myApp)** inside a browser

**Comment by denizque** [comment]
well, the very first time when I generated I was able to access it through http://127.0.0.1:8080
and the reason that I asked assistance here was that I too couldn't see any error in the log.
Now access successfully through /myApp. Thanks a lot for your time.
